// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNr2e2Q8ay-CoPsKgAUrfeFAY5vkCbsDc',
    appId: '1:334286403533:web:0027640e336835b9d07684',
    messagingSenderId: '334286403533',
    projectId: 'fincontrol26-ecbd6',
    authDomain: 'fincontrol26-ecbd6.firebaseapp.com',
    storageBucket: 'fincontrol26-ecbd6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrUXUXp8GYDN0XSM1ftJUEgLoPbfdQbbg',
    appId: '1:334286403533:android:22a953c3b0920855d07684',
    messagingSenderId: '334286403533',
    projectId: 'fincontrol26-ecbd6',
    storageBucket: 'fincontrol26-ecbd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRn8rL1u0T3WXKwq8vNs0mdjxE2HkX5GQ',
    appId: '1:334286403533:ios:fe95b927e3e15fc1d07684',
    messagingSenderId: '334286403533',
    projectId: 'fincontrol26-ecbd6',
    storageBucket: 'fincontrol26-ecbd6.firebasestorage.app',
    iosClientId: '334286403533-237b3a5bg36qj24rlervt9qf188p1i9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fincontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRn8rL1u0T3WXKwq8vNs0mdjxE2HkX5GQ',
    appId: '1:334286403533:ios:fe95b927e3e15fc1d07684',
    messagingSenderId: '334286403533',
    projectId: 'fincontrol26-ecbd6',
    storageBucket: 'fincontrol26-ecbd6.firebasestorage.app',
    iosClientId: '334286403533-237b3a5bg36qj24rlervt9qf188p1i9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fincontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNr2e2Q8ay-CoPsKgAUrfeFAY5vkCbsDc',
    appId: '1:334286403533:web:7d5df7e47627a998d07684',
    messagingSenderId: '334286403533',
    projectId: 'fincontrol26-ecbd6',
    authDomain: 'fincontrol26-ecbd6.firebaseapp.com',
    storageBucket: 'fincontrol26-ecbd6.firebasestorage.app',
  );
}
